# Generated by Django 3.1 on 2025-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_poster_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
